version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - add_ssh_keys:
          fingerprints:
          - "54:19:53:76:bd:06:22:fb:81:75:5d:16:64:b2:53:86"
      - run:
          command: |
            apt update && apt upgrade -y
            apt install -f -y git binutils-arm-linux-gnueabihf
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --depth=1 https://github.com/fredslbn/chime-caf.git -b main builder_kernel
            cd builder_kernel
            
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
